name: Build Inventar
on: [workflow_dispatch,push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Check for backend changes
        env:
          ACTIONS_KEY: ${{ secrets.ACTIONS_KEY }}
        run: |
          RESULT=$(git diff --name-only HEAD^1 HEAD | grep ^backend | wc -l)
          if [ $RESULT -gt 0 ]; then  \
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACTIONS_KEY"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/alexanderjuhn/github-actions/actions/workflows/35108051/dispatches \
            -d '{"ref":"main"}' ; fi
      - name: Check for frontend changes
        env:
          ACTIONS_KEY: ${{ secrets.ACTIONS_KEY }}
        run: |
          RESULT=$(git diff --name-only HEAD^1 HEAD | grep ^frontend | wc -l)
          if [ $RESULT -gt 0 ]; then  \
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACTIONS_KEY"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/alexanderjuhn/github-actions/actions/workflows/43960710/dispatches \
            -d '{"ref":"main"}' ; fi
  
