name: Trigger test
on: [workflow_dispatch,push]

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest
    steps:
      #- name: Trigger Backend Build
      #  uses: actions/github-script@v7
      #  id: trigger-backend
      #  with:
      #    github-token: ${{ secrets.ACTIONS_KEY }}
      #    script: |
      #      github.rest.actions.createWorkflowDispatch({
      #        owner: 'alexanderjuhn',
      #        repo: 'gha-workflows',
      #        workflow_id: 'build_inventar_backend.yml',
      #        ref: 'main',
      #      });
      - name: Watch Backend Build workflow overview
        uses: actions/github-script@v7
        id: watch-backend
        with:
          github-token: ${{ secrets.ACTIONS_KEY }}
          script: |
            result = github.rest.actions.listWorkflowRuns({
              owner: 'alexanderjuhn',
              repo: 'gha-workflows',
              workflow_id: 'build_inventar_backend.yml',
            }).then(result => {
              console.log(result.data);
              return result.data;
            });
      - name: Watch Run
        uses: actions/github-script@v7
        id: watch-run
        with:
          github-token: ${{ secrets.ACTIONS_KEY }}
          script: |
            result = github.rest.actions.getWorkflowRun({
              owner: 'alexanderjuhn',
              repo: 'gha-workflows',
              run_id: ${{ steps.watch-backend.outputs.result.workflow_runs[0].id }},
            }).then(result => {
              console.log(result.data);
              return result.data;
            });
      