name: Trigger test
on: [workflow_dispatch,push]

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Build
        uses: actions/github-script@v7
        id: trigger-backend
        with:
          github-token: ${{ secrets.ACTIONS_KEY }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'alexanderjuhn',
              repo: 'gha-workflows',
              workflow_id: 'build_inventar_backend.yml',
              ref: 'main',
            });
      - name: Watch Backend Build workflow
        uses: actions/github-script@v7
        id: watch-backend
        with:
          github-token: ${{ secrets.ACTIONS_KEY }}
          script: |
            result = github.rest.actions.getWorkflow({
              owner: 'alexanderjuhn',
              repo: 'gha-workflows',
              workflow_id: 'build_inventar_backend.yml',
            }) => console.log(result);
      - name: Testoutput
        run: |
          echo "Backend workflow run id: ${{ steps.watch-backend.outputs.result }}"
